services:
  app:
    build: .
    container_name: whatsapp-app
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=3000
      - HOST=0.0.0.0
      - VITE_SUPABASE_URL=${VITE_SUPABASE_URL}
      - VITE_SUPABASE_PUBLISHABLE_KEY=${VITE_SUPABASE_PUBLISHABLE_KEY}
      - VITE_SUPABASE_PROJECT_ID=${VITE_SUPABASE_PROJECT_ID}
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_PUBLISHABLE_KEY=${SUPABASE_PUBLISHABLE_KEY}
      - SUPABASE_SERVICE_ROLE_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Indma3FmaHR5cHRta3F5aXNlYmtyIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc4MjA2OTA2OSwiZXhwIjoyMDk3NjQ1MDY5fQ._ioP3KcKc3wpa5plC_hpztW2O1n86IyiZZ7q-0Cbc0w
    
    # Vincula a porta ao localhost da VPS de forma segura
    ports:
      - "127.0.0.1:3000:3000"
      
    networks:
      - portainer_default

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whatsmarketing.rule=Host(`whats.legio13.cloud`)"
      - "traefik.http.routers.whatsmarketing.entrypoints=websecure"
      - "traefik.http.routers.whatsmarketing.tls=true"
      - "traefik.docker.network=portainer_default"
      - "traefik.http.services.whatsmarketing.loadbalancer.server.port=3000"

networks:
  portainer_default:
    external: true
